name: R2Inference CI

on:
  push:
    branches:
      - master
      - dev-*
      - feature/ci-experiments
  pull_request:
    branches:
      - dev-*

jobs:
  build:
    runs-on: ubuntu-18.04
    container: ridgerun/r2inference:v0.1.0
    env: 
      PREFIX: /usr/lib/x86_64-linux-gnu/
    steps:
    - uses: actions/checkout@v2
    - name: Install general dependecies
      run: |
        apt-get install -y autoconf automake pkg-config libtool gtk-doc-tools libcpputest-dev
    - name: Install backend version
      run: |
        tar -C /usr/local -xzf /root/r2inference/backends/tensorflow/v1.15.0/libtensorflow-cpu-linux-x86_64-1.15.0.tar.gz
        ldconfig     
    - name: Configure the project
      run: |
        NOCONFIGURE=1 ./autogen.sh
        ./configure --disable-docs --prefix $PREFIX --enable-tensorflow
    - name: Build
      run: make
    - name: Run tests
      run: make check
