name: R2Inference CI

on:
  push:
    branches:
      - master
      - dev-*
      - feature/add-tflite-ci-testing
  pull_request:
    branches:
      - dev-*

jobs:
  build_tensorflow:
    runs-on: ubuntu-18.04
    container: ridgerun/r2inference:v0.1.1
    steps:
    - uses: actions/checkout@v2
    - name: Install backend version
      run: |
        tar -C /usr/local -xzf /root/r2inference/backends/tensorflow/v1.15.0/libtensorflow-cpu-linux-x86_64-1.15.0.tar.gz
        ldconfig     
    - name: Configure the project
      run: |
        NOCONFIGURE=1 ./autogen.sh
        ./configure --disable-docs --enable-tensorflow
    - name: Build
      run: make
    - name: Run tests
      run: make check
  build_tflite:
    runs-on: ubuntu-18.04
    container: ridgerun/r2inference:v0.1.3
    env:
      TENSORFLOW_PATH: /root/r2inference/backends/tflite/v2.0.1/include/tensorflow
      CPPFLAGS: "-I${TENSORFLOW_PATH} -I${TENSORFLOW_PATH}/tensorflow/lite/tools/make/downloads/flatbuffers/include"
    steps:
    - uses: actions/checkout@v2
    - name: Install backend version
      run: |
        cp /root/r2inference/backends/tflite/v2.0.1/binaries/libtensorflow-lite.a /usr/local/lib/    
    - name: Configure the project
      run: |
        export CPPFLAGS="${{ env.CPPFLAGS }}" 
        ./autogen.sh --disable-docs --enable-tflite
