name: R2Inference CI

on:
  push:
    branches:
      - master
      - dev-*
      - feature/ci-experiments
  pull_request:
    branches:
      - dev-*

jobs:
  build:
    runs-on: ubuntu-18.04
    container: ridgerun/r2inference:v0.1.0

    steps:
    - uses: actions/checkout@v2
    - name: Install dependecies
      run: |
        sudo apt install libcpputest-dev
    - name: Configure the project
      run: |
        NOCONFIGURE=1 ./autogen.sh
        ./configure 
